// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/kjushka/di-tests/test_data/action"
	"github.com/kjushka/di-tests/test_data/service"
)

// Injectors from wire.go:

func prepareSomeActionWithParams(a int, s string, f1 float32, f2 float64) action.SomeService {
	someSubSubService1 := service.NewSomeSubSubService1WithParam(f1)
	someSubSubService2 := service.NewSomeSubSubService2WithParam(f2)
	someSubService1 := service.NewSomeSubService1WithParam(s, someSubSubService1, someSubSubService2)
	someSubService2 := service.NewSomeSubService2WithoutParam(someSubSubService1)
	someService := service.NewSomeServiceWithParam(a, someSubService1, someSubService2)
	return someService
}

func prepareSomeActionWithoutParams(f1 float32, f2 float64) action.SomeService {
	someSubSubService1 := service.NewSomeSubSubService1WithParam(f1)
	someSubSubService2 := service.NewSomeSubSubService2WithParam(f2)
	someSubService1 := service.NewSomeSubService1WithoutParam(someSubSubService1, someSubSubService2)
	someSubService2 := service.NewSomeSubService2WithoutParam(someSubSubService1)
	someService := service.NewSomeServiceWithoutParam(someSubService1, someSubService2)
	return someService
}
